name: Tests

on: workflow_dispatch

jobs:
  test:
    strategy:
        matrix:
          include:
          - name: iOS (arm64)
            os: macos-14
            suffix: ''
            triplet: arm64-ios-release
            host_triplet: arm64-osx-release
            ccache_path: ~/Library/Caches/ccache

    name: '${{ matrix.name }}'
    runs-on: '${{ matrix.os }}'
    
    steps:
    - name: Try xcrun
      run: |
        sudo xcode-select -s /Library/Developer/CommandLineTools
        xcrun --sdk iphoneos --show-sdk-path
